const alle = ["gr1", "gr2", "gr3"];

export const planDo = [
    {
        stunde: 1,
        titel: "Betriebssysteme II",
        kurz: "BS2",
        raum: "G023b",
        dozent: "Prof. Dr. Tilo Müller",
        moodle: "https://moodle.hof-university.de/course/view.php?id=4544",
        gruppe: alle,
    },
    {
        stunde: 2,
        titel: "Rechnernetzwerke II",
        kurz: "RN2",
        raum: "B023",
        dozent: "Dipl.-Inf. Stefan Müller",
        moodle: "https://moodle.hof-university.de/course/view.php?id=4565",
        gruppe: alle,
    },
    {
        stunde: 3,
        titel: "Betriebssyteme II - Ü1",
        kurz: "BS2 - Ü1",
        raum: "D242",
        dozent: "Prof. Dr. Tilo Müller",
        moodle: "https://moodle.hof-university.de/course/view.php?id=4544",
        gruppe: "gr1",
    },
    {
        stunde: 3,
        titel: "Geschäftsprozessmodellierung - Ü2",
        kurz: "GPM - Ü2",
        raum: "G028/029",
        dozent: "Prof. Dr. Florian Kupsch",
        moodle: "https://moodle.hof-university.de/course/view.php?id=4370",
        gruppe: "gr2",
    },
    {
        stunde: 4,
        titel: "Algorithmen und Datenstrukturen",
        kurz: "AlgoDat",
        raum: "B023",
        dozent: "Prof. Dr. Peter Stöhr",
        moodle: "https://moodle.hof-university.de/course/view.php?id=4326",
        gruppe: alle,
    },
    {
        stunde: 5,
        titel: "",
        kurz: "",
        raum: "",
        dozent: "",
        moodle: "",
        gruppe: alle,
    },
]